name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Prepare linters
        run: |
          nix develop --command bash -c "vale sync && pre-commit install --install-hooks"

      - name: Run linters
        run: |
          nix develop --command bash -c "pre-commit run --all-files"
